

#Getting Started with Numpy
In this practical we gonna study about NumPY i.e. Numerical Python. This is the library that provides us with the functions over multidimensional array objects, Numerical and logical operations over the arrays, operations related to Linear Algebra. 

In [ ]:
#Importing the required libraries
import numpy as np


#Numpy Functions

#Array
it is the most important object in the Numpy. Also called as N-dimensional array
#Syntax
np.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)



Declaring array

In [ ]:
#declaring the 1d Array
a = np.array([1,2,3,4,5],dtype=int)
a

array([1, 2, 3, 4, 5])

In [ ]:
#2) Declaring the 2D array
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype="complex")
a

array([[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
       [ 5.+0.j,  6.+0.j,  7.+0.j,  8.+0.j],
       [ 9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j]])

In [ ]:
#3)Knowing the type of declared array
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
type(a)

numpy.ndarray

In [ ]:
# 4) Getting the Dimension of the array
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.ndim

2

In [ ]:
# 5) Getting the data type of the array elements 
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.dtype

dtype('int64')

In [ ]:
# 6) Getting the size of the array
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.size

12

In [ ]:
# 7) Getting the Shape of the array i.e. how many rows and columns are present in the array
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.shape

(3, 4)

In [ ]:
# 8) Reshaping the array
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#Basic Arithmatic Operations

In [ ]:
#9) Concatenating the two arrays 
a=np.array([[1,2,3,4],[1,7,0,6]])
b=np.array([[2,5,6,8],[3,7,4,9]])
c=np.concatenate((a,b))
print(c)
# Now concatenating two arrays based on rows i.e. Axis = 1
d=np.concatenate((a,b),axis=1)
print(d)

[[1 2 3 4]
 [1 7 0 6]
 [2 5 6 8]
 [3 7 4 9]]
[[1 2 3 4 2 5 6 8]
 [1 7 0 6 3 7 4 9]]


In [ ]:
# 10) Adding elements of the two arrays 
a=np.array([[1,2,3,4],[1,7,0,6]])
b=np.array([[2,5,6,8],[3,7,4,9]])
c=np.add(a,b)
print(a+b)
c

[[ 3  7  9 12]
 [ 4 14  4 15]]


array([[ 3,  7,  9, 12],
       [ 4, 14,  4, 15]])

In [ ]:
# 11) Subtracting the array elements of two arrays
a=np.array([[1,2,3,4],[1,7,0,6]])
b=np.array([[2,5,6,8],[3,7,4,9]])
c=np.subtract(a,b)
print(a-b)
c

[[-1 -3 -3 -4]
 [-2  0 -4 -3]]


array([[-1, -3, -3, -4],
       [-2,  0, -4, -3]])

In [ ]:
#12) Taking the product of two arrays
a=np.array([[1,2,3,4],[1,7,0,6]])
b=np.array([[2,5,6,8],[3,5,4,9]])
c=np.prod((a,b))
print(a*b)
c

[[ 2 10 18 32]
 [ 3 35  0 54]]


0

In [ ]:
#13) Taking Matrix multiplication of the two matrices
a=np.array([[1,2,3,4],[1,7,0,6]])
b=np.array([[2,5],[6,8],[3,5],[4,9]])
print(a@b)    #Matrix Product

[[ 39  72]
 [ 68 115]]


In [ ]:
# 14) Taking dor product of two matrices
a=np.array([[1,2,3,4],[1,7,0,6]])
b=np.array([[2,5],[6,8],[3,5],[4,9]])
a.dot(b)      #matrix Product

array([[ 39,  72],
       [ 68, 115]])

In [ ]:
# 15) Taking sum of all elements present in the matrix
a=np.array([[1,2,3,4],[1,7,0,6]])
a.sum()

24

In [ ]:
# 16) Getting the minimum element from the declared matrix
a=np.array([[1,2,3,4],[1,7,0,6]])
a.min()

0

In [ ]:
# 17) Getting the maximum element from the declared array or the matrix
a=np.array([[1,2,3,4],[1,7,0,6]])
a.max()

7

In [ ]:
# 18) Knowing the sum, min and cumulative sum of column and row separately
a=np.array([[1,2,3,4],[1,7,0,6]])
print(a.sum(axis=0))
print(a.min(axis=1))
print(a.cumsum(axis=1))

[ 2  9  3 10]
[1 0]
[[ 1  3  6 10]
 [ 1  8  8 14]]


In [ ]:
# 19) Knowing the exponential and squareroot value of each element present in the array
b=np.arange(5)
print(b)
print(np.exp(b))
print(np.sqrt(b))

[0 1 2 3 4]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[0.         1.         1.41421356 1.73205081 2.        ]


In [ ]:
# 20) Getting the seqential no. with defined space
c=np.arange(6)
d=np.arange(1,10,2)
c
d

array([1, 3, 5, 7, 9])

Printing the evenly spaced integer within Range and How much space there should be between each interger

In [ ]:
# 21) Another function same as arange
a=np.linspace(1,30,5)
a

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

Converting the list in the numpy array

In [ ]:
# 22) Converting the list into Numpy array
list1 = [1,2,3,4,5]
np_arr=np.array(list1)
np_arr1=np.asarray(list1)
np_arr1

array([1, 2, 3, 4, 5])

Printing the random Matrix of random intergers within a range

In [ ]:
# 23) Printing the random array element from the defined range
a=np.random.randint(10,100,(5,5))
a

array([[77, 91, 33, 63, 77],
       [24, 93, 93, 96, 52],
       [40, 33, 58, 67, 45],
       [95, 23, 15, 90, 64],
       [83, 63, 99, 68, 51]])

Slicing the array

In [ ]:
#24) Slicing the array
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[1,3])
print(a[4::2])
print(a[:5])
print(a[-3:-1])


8
[]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]


Printing the array 

In [ ]:
#25) Printing the array element in various types
print(np.arange(10000))
print(np.arange(10000).reshape(100, 100))


#To force the numpy to print all the array element
np.set_printoptions(threshold=sys.maxsize)
print(np.arange(300).reshape(6,50))

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
   36  37  38  39  40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
   68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
   86  87  88  89  90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
  136 137 138 139 140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
  168 169 170 171 172 173 174 175 176 177

In [ ]:
#26) Taking transpose of the matrix
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.T)
print(np.transpose(a))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
# 27) copying element of the given array
cpy = a.copy()
print(cpy)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 28) Viewing does not own the data, any change made to the view will affect original array and viceversa
x = a.view()
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#29) Checking if copy and view owes the data with the help of base()
d = a.copy()
M = a.view()

print(d.base)  #Copy returns none
print(M.base)  # view returns original array

None
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 30) Flattening the arrays
d = a.reshape(-1)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#31) iterating through the following 3d array
dam = np.array([[[1,2,3],[4,5,6]]])
for element in np.nditer(dam):
  print(element,)

1
2
3
4
5
6


In [ ]:
#32) Enumerated iterarions using ndenumerate()
#Enumerate meand mentioning sequence no. of something one by one 
arr2=np.array([1,2,3])
for index,element in np.ndenumerate(arr2):
  print(index,element)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
#33) Joining using Stack
b = np.array([1,2,3])
c = np.array([4,5,6])
d= np.stack((b,c),axis =1)
print(d)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#34) Stacking along rows using hstack()
d =np.hstack((b,c))
print(d)

[1 2 3 4 5 6]


In [ ]:
#35 Stacking a;ong columns using vstack()
d=np.vstack((b,c))
print(d)

[[1 2 3]
 [4 5 6]]


In [ ]:
#36) Stacking along Height (depth) using dstack()
d= np.dstack

In [ ]:
#37) Sorting
arr = [3,2,5,7,6,8,8,9,2,1,0]
arr.sort()
print(arr)

[0, 1, 2, 2, 3, 5, 6, 7, 8, 8, 9]


In [ ]:
#38) Generating the random interger from range 1 to 100
i = np.random.randint(1,100,1)
print(i) 

#generating the random float from range 1 to 100
j = np.random.rand(1)
print(j)

[7]
[0.8877546]


In [ ]:
#39) Generating the Random Array
i = np.random.randint(100,size = (5))
print(i)

#Generate 2-D array randomly
j = np.random.randint(100,size = (4,5))
print(j)

#Generate Random Number from Array --> choice()
i = np.random.choice([2,4,5,6,2,3])
print(i)

[66 23 81 73 77]
[[22 16 59 26 20]
 [ 4 79 63 48 76]
 [12 37 92 29 20]
 [85 80 92 89 23]]
3


In [ ]:
#40) Trignometric Function
i = np.sin(np.pi/2)
print(i)

1.0


In [ ]:
#41) Converting all of the values in following array to randians
j = np.array([90,180,270,360])
k = np.deg2rad(j)
print(k)

#similarly rad2deg() function can be used to convert the radian to degree

[1.57079633 3.14159265 4.71238898 6.28318531]


In [ ]:
#42) finding the angle 
l = np.arcsin(1.0)
print(l)

1.5707963267948966


In [ ]:
#43) Hypotaneous
base = 3
perp =4
l = np.hypot(base,perp)
print(l)

5.0


In [ ]:
#44) Greatest Common devisor
#also known as HCF
num1 =6
num2 = 69
l = np.gcd(num1,num2)
print(l)

#reduce used for arrays
arr = np.array([20,8,32,36,16])
l = np.gcd.reduce(arr)
print(l)

3
4


In [ ]:
#45) Difference (Discrete)
arr = np.array([10,20,25,15])
newarr = np.diff(arr)
print(newarr)

#Computing the difference (Discrete) of the array twice
newarr = np.diff(arr, n=2)
print(newarr)

[ 10   5 -10]
[ -5 -15]


In [ ]:
#46) Product 
arr = np.array([1,2,3,4,5])
newArr = np.product(arr)
print(newArr)

120


In [ ]:
#47)Product of the two array
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a3 = np.product([a1,a2])
print(a3)

3628800


In [ ]:
#48) Product of array over axis
a4 = np.product([a1,a2],axis = 1)
print(a4)

[  120 30240]


In [ ]:
#49) Cumulative Product
a5 = np.array([1,2,3,4])
newArr1 = np.cumprod(a5)
print(newArr1)

#similarly Cumulative Sum
a6 = np.sum([a1,a2])
print(a6)

[ 1  2  6 24]
55


In [ ]:
#50) Capitalising Only first character of the string
print(np.char.capitalize('hello world'))

# title
print(np.char.title("hello how are you"))

# lower()
print(np.char.lower(['HELLO', 'WORLD']))
print(np.char.lower("HELLO"))

#replace
print(np.char.replace('He is a good boy','is','was'))

Hello world
Hello How Are You
['hello' 'world']
hello
He was a good boy
